### ISSUE TITLE
Website link for companies is broken

### ISSUE THREAD

**Issue by mehdibaha** [ForumOrganisation/forumorg#167]
![image](https://user-images.githubusercontent.com/2317255/36380529-e5f7472c-1582-11e8-9b61-746e185f4aa6.png)

**Comment by mehdibaha** [comment]
This is fixed in PR #170

**Comment by mehdibaha** [comment]
Where is this fixed in your PR #170 @momeg ?

**Comment by momeg** [comment]
There were some copy paste issues in the website column of the csv .I fixed the ones I found but I can't be  sure I got all of them .If you still see a problem somewhere please tell me .
