### ISSUE TITLE
Archive last edition CVs

### ISSUE THREAD

**Issue by momeg** [ForumOrganisation/forumorg#174]

**Comment by TheHeisenberg** [comment]
Since this is not possible, we should maybe add a date parameter for CVs in order to know when they have been added.

**Comment by mehdibaha** [comment]
Good idea! This shouldn't be very hard. Currently, we update CVs like this:

`get_db().users.update_one({'id': current_user.id}, {'$set': {'profile.resume_id': str(oid)}})`

Maybe create a resume key inside profile, with nested keys: id, upload_date ?
